name = "HudlTest"
version = "0.1.0"
description = "A demonstration test framework which tests the login functionality of https://www.hudl.com/"
license = "3.0-or-later"
authors = "Josh Simpson <josholiversimpson@hotmail.com>"

[tool.pytest.ini_options]
pythonpath = "."
addopts = [
    "--import-mode=importlib",
]